### ISSUE TITLE
callback 

### ISSUE THREAD

**Issue by miatoszs** [OpenianDevelopement/Menhera-Chan#1] opened 2021-01-19 14:00 UTC
DISCORD_CALLBACK_URI what should i write here if i use localhost?

**Comment by norowachi** [comment] 2021-01-19 14:02
http://localhost:3000 for example

**Comment by miatoszs** [comment] 2021-01-19 14:15
and how can i use the dashboard not: https://dashboard.menhera-chan.in/

**Comment by norowachi** [comment] 2021-01-19 14:19
You can open http://localhost:3001/ (if you didn't change the port in the .env file)

**Comment by miatoszs** [comment] 2021-01-19 14:21
but after the authorize it take me to the main page

**Comment by norowachi** [comment] 2021-01-19 14:23
welp that's an issue that need to get fixed 
for now if i can't do it @rohank05 will fix it and thanks for reporting that.

**Comment by miatoszs** [comment] 2021-01-19 14:25
Thank you for helping me

**Comment by norowachi** [comment] 2021-01-19 15:08
It should be fixed now (well some of it)

**Comment by atadamos** [comment] 2021-01-19 15:12
the issue is here: /main/views/index.ejs line 25

**Closed as completed** 2021-01-19 15:11 UTC
Labels: bug, question

**Comment by norowachi** [comment] 2021-01-19 15:15
> the issue is here: /main/views/index.ejs line 25

well that's with the main page, I fixed the dashboard's back-end thingies for now
